import type { TrumpCorpusEntry } from './trump.scoring';

export const TRUMP_TRAINING_CORPUS: TrumpCorpusEntry[] = [
  { content: 'Iran attacked our military assets and we will respond immediately with overwhelming force tonight.', criticality: 10, isBreaking: true },
  { content: 'Any retaliation will be met with force far greater than what was witnessed tonight.', criticality: 10, isBreaking: true },
  { content: 'A whole civilization will die tonight if this war continues.', criticality: 10, isBreaking: true },
  { content: 'I am imposing 100% tariffs on all imports from China effective immediately.', criticality: 10, isBreaking: true },
  { content: 'All goods from China will face emergency tariffs and export bans starting now.', criticality: 10, isBreaking: true },
  { content: 'The Secretary of State has resigned effective immediately after tonight’s emergency meeting.', criticality: 10, isBreaking: true },
  { content: 'The Secretary of Defense has been fired and a replacement will be announced tonight.', criticality: 10, isBreaking: true },
  { content: 'We have ordered strikes on nuclear facilities and additional bombers are ready.', criticality: 10, isBreaking: true },
  { content: 'Bombardment of military targets begins now and more missiles are on the way.', criticality: 10, isBreaking: true },
  { content: 'A naval blockade is now in effect and all tankers will be stopped.', criticality: 9, isBreaking: true },
  { content: 'Export controls on advanced semiconductor equipment to China are expanded nationwide.', criticality: 9, isBreaking: true },
  { content: 'Sanctions and trade restrictions will hit every company dealing with Iran.', criticality: 9, isBreaking: true },
  { content: 'National security leadership is being removed after the intelligence crisis.', criticality: 9, isBreaking: true },
  { content: 'Troops are being deployed after the missile strike and our response is coming.', criticality: 9, isBreaking: true },
  { content: 'Emergency powers are now on the table if this crisis escalates again.', criticality: 8, isBreaking: true },
  { content: 'Massive tariffs will hit foreign steel and auto imports if talks fail.', criticality: 8, isBreaking: true },
  { content: 'The Pentagon and Treasury are coordinating an immediate sanctions package.', criticality: 8, isBreaking: true },
  { content: 'A ceasefire is collapsing and the military is preparing new strikes.', criticality: 8, isBreaking: true },
  { content: 'I have named William Pulte to be Acting Director of National Intelligence, who will take over on June 19.', criticality: 4, isBreaking: false },
  { content: 'Record $327.1 Billion Exports Help Shrink U.S. Trade Deficit.', criticality: 3, isBreaking: false },
  { content: 'Early Voting is underway in Georgia and Burt Jones has my Complete and Total Endorsement.', criticality: 1, isBreaking: false },
  { content: 'Congratulations to the Ohio State Senate for passing Senate Joint Resolution 10 on voter ID.', criticality: 2, isBreaking: false },
  { content: 'I will be doing a TeleRally LIVE at 5:30 P.M. EST for Senator Lindsey Graham and Pamela Evette.', criticality: 1, isBreaking: false },
  { content: 'Congressman Russell Fry has my Complete and Total Endorsement for Re-Election.', criticality: 1, isBreaking: false },
  { content: 'Congressman William Timmons has my Complete and Total Endorsement for Re-Election.', criticality: 1, isBreaking: false },
  { content: 'We are investigating a major fraud and Congress will hold hearings.', criticality: 5, isBreaking: false },
  { content: 'The economy needs lower inflation and a better trade deal.', criticality: 4, isBreaking: false },
  { content: 'A court decision today could change the election conversation.', criticality: 4, isBreaking: false },
  { content: 'We had a strong rally tonight and the crowd was incredible.', criticality: 2, isBreaking: false },
  { content: 'Thank you to everyone in Michigan for the tremendous support.', criticality: 1, isBreaking: false },
  { content: 'The fake news media is at it again, but we are winning.', criticality: 1, isBreaking: false },
  { content: 'A beautiful day, great meeting, and more endorsements coming soon.', criticality: 1, isBreaking: false },
];
